apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: social-media-scrappers # Nom unique de l'application dans ArgoCD
  namespace: argocd # Doit s'exécuter dans le namespace ArgoCD
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default # Le projet ArgoCD par défaut
  source:
    repoURL: https://github.com/kehe0014/social-media-scrapper.git # URL de votre dépôt Git
    targetRevision: main # La branche à surveiller
    path: k8s # Le sous-dossier où ArgoCD trouvera les manifestes (deployment.yaml, service.yaml, etc.)
  destination:
    server: https://kubernetes.default.svc # Cible l'API Server interne du cluster K3s
    namespace: my-app # Le namespace de destination de l'application (correspond à votre deployment.yaml)
  syncPolicy:
    automated: # Active la synchronisation automatique
      prune: true # Supprime les ressources qui n'existent plus dans Git
      selfHeal: true # Corrige l'état du cluster s'il diverge de Git
    syncOptions:
    - CreateNamespace=true # ArgoCD créera le namespace 'my-app' si nécessaire
    - ApplyOutOfSyncOnly=true # N'applique les changements que lorsque l'état diverge