name: CI/CD Pipeline to K3S via ArgoCD GitOps

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'k8s/deployment.yaml'

env:
  PYTHON_VERSION: '3.10'
  DOCKER_USERNAME: tdksoft341
  REGISTRY: docker.io
  IMAGE_NAME: social-media-dashboard
  IMAGE_TAG: ${{ github.sha }}
  K8S_NAMESPACE: my-app
  K3S_HOST: 178.254.23.139
  K3S_USERNAME: hkengne
  APP_DOMAIN: http://178.254.23.139
  K8S_MANIFESTS_PATH: k8s/
  GH_PAT: ${{ secrets.GH_PAT }}

jobs:
  build-and-push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PAT }}

      - name: Build and Push Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

  deploy:
    name: Deploy on K3S via ArgoCD
    runs-on: ubuntu-latest
    needs: build-and-push
    permissions:
      contents: write
      actions: write
      checks: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
          
      - name: Update Deployment Manifest with New Image Tag
        uses: mikefarah/yq@v4 
        with:
          cmd: |
            export NEW_TAG="${{ env.REGISTRY }}/${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"
            yq -i '.spec.template.spec.containers[0].image = env(NEW_TAG)' ${{ env.K8S_MANIFESTS_PATH }}/deployment.yaml

      - name: Ensure Service is ClusterIP
        run: |
          yq -i '.spec.type = "ClusterIP"' ${{ env.K8S_MANIFESTS_PATH }}/service.yaml

      - name: Ensure Ingress has correct path
        run: |
          yq -i '.spec.rules[0].http.paths[0].path = "/sm-scrapper"' ${{ env.K8S_MANIFESTS_PATH }}/ingress.yaml
          yq -i '.spec.rules[0].http.paths[0].backend.service.name = "social-media-scrapper-service"' ${{ env.K8S_MANIFESTS_PATH }}/ingress.yaml
          yq -i '.spec.rules[0].http.paths[0].backend.service.port.number = 80' ${{ env.K8S_MANIFESTS_PATH }}/ingress.yaml

      - name: Commit and Push Manifest Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "CD: Update image tag and ingress path for social-media-scrapper to ${{ github.sha }}"
          file_pattern: |
            ${{ env.K8S_MANIFESTS_PATH }}/deployment.yaml
            ${{ env.K8S_MANIFESTS_PATH }}/service.yaml
            ${{ env.K8S_MANIFESTS_PATH }}/ingress.yaml
          token: ${{ secrets.GH_PAT }}
          git_pull_options: --rebase

      - name: Apply Kubernetes Manifests
        uses: azure/k8s-deploy@v5
        with:
          namespace: ${{ env.K8S_NAMESPACE }}
          manifests: |
            ${{ env.K8S_MANIFESTS_PATH }}/deployment.yaml
            ${{ env.K8S_MANIFESTS_PATH }}/service.yaml
            ${{ env.K8S_MANIFESTS_PATH }}/ingress.yaml
          kubeconfig: ${{ secrets.KUBECONFIG }}
