name: Application Health Check

on:
  workflow_dispatch:  # Permet de lancer manuellement
  push:
    branches: [main, develop]
    paths:
      - 'app.py'
      - 'requirements.txt'

env:
  STAGING_SERVER: 178.254.23.139
  DEPLOY_USER: deploy
  APP_NAME: social-media-downloader
  APP_PATH: /var/www/streamlit-app

jobs:
  health-check:
    name: Start Application and Health Check
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code (for reference)
      uses: actions/checkout@v4
      
    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY_1BLU }}" > ~/.ssh/staging_key
        chmod 600 ~/.ssh/staging_key
        ssh-keyscan -H $STAGING_SERVER >> ~/.ssh/known_hosts

    - name: Start Streamlit Application via Systemd
      run: |
        echo "🚀 Starting Streamlit application via systemd..."
        ssh -i ~/.ssh/staging_key \
            -o ConnectTimeout=10 \
            $DEPLOY_USER@$STAGING_SERVER "
            set -e
            echo '🔧 Managing Streamlit application via systemd...'
            
            # Vérifier et démarrer le service systemd
            if sudo systemctl is-active streamlit-app > /dev/null; then
              echo '🔄 Restarting existing Streamlit service...'
              sudo systemctl restart streamlit-app
            else
              echo '🚀 Starting Streamlit service...'
              sudo systemctl start streamlit-app
            fi
            
            # Attendre que le service démarre
            echo '⏳ Waiting for service to start...'
            sleep 10
            
            # Vérifier le statut du service
            echo '📊 Streamlit service status:'
            sudo systemctl status streamlit-app --no-pager
            
            # Vérifier que le service est actif
            if sudo systemctl is-active streamlit-app > /dev/null; then
              echo '✅ Streamlit service is running'
            else
              echo '❌ Streamlit service failed to start'
              sudo journalctl -u streamlit-app -n 20 --no-pager
              exit 1
            fi
            
            # Vérifier le port d'écoute
            echo '🔍 Checking if port 8501 is listening...'
            if sudo netstat -tuln | grep ':8501' > /dev/null; then
              echo '✅ Port 8501 is listening'
            else
              echo '❌ Port 8501 is not listening'
              exit 1
            fi
        "

    - name: Health Check - Basic Connectivity
      run: |
        echo "🏥 Performing health checks..."
        echo "🔗 Testing basic connectivity to Streamlit app..."
        
        # Test de connexion basique avec retry
        MAX_RETRIES=12
        RETRY_COUNT=0
        
        while [ $RETRY_COUNT -lt $MAX_RETRIES ]; do
          echo "Health check attempt $((RETRY_COUNT + 1))/$MAX_RETRIES"
          
          # Essayer plusieurs endpoints Streamlit
          if curl -f -s -o /dev/null -w "HTTP Status: %{http_code}\n" \
               --connect-timeout 10 \
               http://$STAGING_SERVER:8501/_stcore/health 2>/dev/null; then
            echo "✅ Streamlit health endpoint responding"
            break
          elif curl -f -s -o /dev/null -w "HTTP Status: %{http_code}\n" \
               --connect-timeout 10 \
               http://$STAGING_SERVER:8501/ 2>/dev/null; then
            echo "✅ Streamlit main endpoint responding"
            break
          else
            RETRY_COUNT=$((RETRY_COUNT + 1))
            if [ $RETRY_COUNT -lt $MAX_RETRIES ]; then
              echo "⏳ Health check failed, retrying in 5 seconds..."
              sleep 5
            fi
          fi
        done
        
        if [ $RETRY_COUNT -eq $MAX_RETRIES ]; then
          echo "❌ Health check failed after $MAX_RETRIES attempts"
          echo "Debug info:"
          ssh -i ~/.ssh/staging_key \
              -o ConnectTimeout=10 \
              $DEPLOY_USER@$STAGING_SERVER "
              echo '=== Service Status ==='
              sudo systemctl status streamlit-app --no-pager
              echo '=== Recent Logs ==='
              sudo journalctl -u streamlit-app -n 20 --no-pager
              echo '=== Port Check ==='
              sudo netstat -tuln | grep ':8501' || echo 'Port 8501 not listening'
              echo '=== Process Check ==='
              ps aux | grep streamlit | grep -v grep || echo 'No streamlit processes'
          "
          exit 1
        fi

    - name: Health Check - Streamlit API
      run: |
        echo "🔍 Testing Streamlit specific endpoints..."
        
        # Test de l'endpoint principal de Streamlit
        echo "Testing main Streamlit endpoint..."
        RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" \
          --connect-timeout 10 \
          http://$STAGING_SERVER:8501/)
        
        if [ "$RESPONSE" = "200" ] || [ "$RESPONSE" = "302" ]; then
          echo "✅ Streamlit main endpoint responding (HTTP $RESPONSE)"
        else
          echo "⚠️ Streamlit main endpoint returned HTTP $RESPONSE"
        fi
        
        # Test de l'endpoint de santé Streamlit
        echo "Testing Streamlit health endpoint..."
        HEALTH_RESPONSE=$(curl -s --connect-timeout 10 http://$STAGING_SERVER:8501/_stcore/health)
        if echo "$HEALTH_RESPONSE" | grep -q "ok" || [ "$HEALTH_RESPONSE" = "" ]; then
          echo "✅ Streamlit health endpoint responding"
        else
          echo "⚠️ Streamlit health endpoint: $HEALTH_RESPONSE"
        fi

    - name: Health Check - Application Logic
      run: |
        echo "🧪 Testing application specific functionality..."
        
        # Vérifier que l'application charge correctement
        echo "Testing application load..."
        APP_CONTENT=$(curl -s --connect-timeout 10 http://$STAGING_SERVER:8501/)
        if echo "$APP_CONTENT" | grep -i "social.media.downloader\|streamlit\|téléchargeur" > /dev/null; then
          echo "✅ Application UI loaded successfully"
        else
          echo "⚠️ Application UI might not be loading as expected"
          echo "First 500 chars of response:"
          echo "$APP_CONTENT" | head -c 500
        fi

    - name: Verify Application Status
      run: |
        echo "🔍 Verifying application status..."
        ssh -i ~/.ssh/staging_key \
            -o ConnectTimeout=10 \
            $DEPLOY_USER@$STAGING_SERVER "
            set -e
            echo '📊 Application status verification:'
            
            # Vérifier le service systemd
            echo '=== Systemd Service Status ==='
            sudo systemctl status streamlit-app --no-pager
            
            # Vérifier les logs récents
            echo '=== Recent Service Logs ==='
            sudo journalctl -u streamlit-app -n 10 --no-pager
            
            # Vérifier les processus
            echo '=== Process Status ==='
            ps aux | grep streamlit | grep -v grep
            
            # Vérifier la consommation mémoire
            echo '=== Memory Usage ==='
            ps aux --sort=-%mem | head -3
            
            # Vérifier les connexions réseau
            echo '=== Network Connections ==='
            sudo netstat -tuln | grep ':8501'
            
            # Vérifier les logs de l'application
            echo '=== Application Logs ==='
            if [ -f '$APP_PATH/streamlit.log' ]; then
              tail -10 '$APP_PATH/streamlit.log'
            else
              echo 'No application log file found'
            fi
            
            echo '✅ Application status verification completed'
        "

    - name: Final Health Report
      run: |
        echo "📊 FINAL HEALTH CHECK REPORT"
        echo "============================"
        echo "✅ Application deployed successfully"
        echo "✅ Streamlit service started via systemd"
        echo "✅ Health checks passed"
        echo "✅ Network connectivity confirmed"
        echo ""
        echo "🌐 Application URL: http://$STAGING_SERVER:8501"
        echo "📁 Deployment path: $APP_PATH"
        echo "👤 Running as user: $DEPLOY_USER"
        echo "🔧 Service: streamlit-app.service"
        echo ""
        echo "🎉 Deployment and health checks completed successfully!"

    - name: Cleanup SSH
      run: |
        rm -f ~/.ssh/staging_key
        echo "✅ SSH key cleaned up"